We are going to use the famous iris data set for our KNN example. 


The dataset consists of four attributes: sepal-width, sepal-length, petal-width and petal-length. 



These are the attributes of specific types of iris plant. 


The task is to predict the class to which these plants belong. There are three classes in the dataset: Iris-setosa, Iris-versicolor and Iris-virginica. 


Further details of the dataset are available here.
https://scikit-learn.org/stable/auto_examples/datasets/plot_iris_dataset.html

## Question

Please import, preprocess the data, train-test split, feature scale it, make predictions, and please evaluate it. 

Please also calculate the error rate for K values of 1 to 40. 

In each iteration the mean error for predicted values of test set is calculated and the result is appended to the error list.

The next step is to plot the error values against K values.

In [60]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.neighbors import KNeighborsClassifier

In [61]:
df = pd.read_csv('https://raw.githubusercontent.com/uiuc-cse/data-fa14/gh-pages/data/iris.csv')
data = df.iloc[:,:-1]
goal = df['species']

In [62]:
X = data.to_numpy()
y = goal.to_numpy()

In [63]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [65]:
for k in range(1,41):
    knn = KNeighborsClassifier(n_neighbors=k, metric='euclidean')
    knn.fit(X_train, y_train)

    y_pred = knn.predict(X_test)
    
    print('Confusion Matrix:')
    print(confusion_matrix(y_test, y_pred))
    print('Accuracy:')
    print(accuracy_score(y_test, y_pred))
    print('#################')

Confusion Matrix:
[[13  0  0]
 [ 0 16  0]
 [ 0  0  9]]
Accuracy:
1.0
#################
Confusion Matrix:
[[13  0  0]
 [ 0 16  0]
 [ 0  0  9]]
Accuracy:
1.0
#################
Confusion Matrix:
[[13  0  0]
 [ 0 16  0]
 [ 0  0  9]]
Accuracy:
1.0
#################
Confusion Matrix:
[[13  0  0]
 [ 0 16  0]
 [ 0  0  9]]
Accuracy:
1.0
#################
Confusion Matrix:
[[13  0  0]
 [ 0 16  0]
 [ 0  0  9]]
Accuracy:
1.0
#################
Confusion Matrix:
[[13  0  0]
 [ 0 16  0]
 [ 0  0  9]]
Accuracy:
1.0
#################
Confusion Matrix:
[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]
Accuracy:
0.9736842105263158
#################
Confusion Matrix:
[[13  0  0]
 [ 0 16  0]
 [ 0  0  9]]
Accuracy:
1.0
#################
Confusion Matrix:
[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]
Accuracy:
0.9736842105263158
#################
Confusion Matrix:
[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]
Accuracy:
0.9736842105263158
#################
Confusion Matrix:
[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]
Accuracy:
0.9736842105263158
#